// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8DYLoJHmQJl6mstawMF9FahcSw6VbYpM',
    appId: '1:86009759503:web:39014fd29a763f6213207a',
    messagingSenderId: '86009759503',
    projectId: 'my-portfolio-24582',
    authDomain: 'my-portfolio-24582.firebaseapp.com',
    storageBucket: 'my-portfolio-24582.firebasestorage.app',
    measurementId: 'G-F9JZM2YXP7',
    databaseURL: 'https://my-portfolio-24582-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvkui2bIWAH9WDpeIMLeeU-tAzkhfU-o',
    appId: '1:86009759503:android:0233e5210b68e45013207a',
    messagingSenderId: '86009759503',
    projectId: 'my-portfolio-24582',
    storageBucket: 'my-portfolio-24582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjlpc1PyhRhB7lOTx_fgKnOC6Yf1l51Zc',
    appId: '1:86009759503:ios:0f1c46b61e3c7b9813207a',
    messagingSenderId: '86009759503',
    projectId: 'my-portfolio-24582',
    storageBucket: 'my-portfolio-24582.firebasestorage.app',
    iosBundleId: 'com.avd97.myPortfolio',
  );
}
